### ISSUE TITLE
Use redux toolkit instead of pure redux

### ISSUE THREAD

**Issue by mradenovic** [TarikHuber/react-most-wanted#116]
I really like where this can go with #106. I would like to work on implementing [@reduxjs/toolkit](https://redux-toolkit.js.org/introduction/quick-start). It should make boilerplate code smaller and includes `thunk` by default.

**Comment by TarikHuber** [comment]
Hi @mradenovic . I never used redux toolkit and have a hard time to understand why it is needed. I have no problem with redux boilerplate because the database stuff can be abstracted to handle all data and for the rest and small stuff there is simpleValue and persistentValue. To be honest I can't even remember when was the last time I created a redux action or reducer. I would leave the `base-shell` with the minimum of needed libraries as possible. Thinking even to remove some that are already inside like the update provider and others not needed in realy all projects. What do you think of making it optional? We could have a default function to create the store and you could use your own sending it trough the configs?

**Comment by TarikHuber** [comment]
@mradenovic I just started today with the material-ui-shell It uses base-shell as base ( that is the reason for the name ;) ) We just make config changes and merge them in the demo/production project. You can see a basic example I made today with the LandingPage. The next step there is to make it similar to rmw-shell but without firebase. We will ofcourse use only Material UI for the UI and customise if needed. I will try to make more examples tomorrow. Also a documentation would be great. Maybs even an ilustration how one shell is above the other. rmw-shell will be modified so it depends also on the base shell.
