### ISSUE TITLE
Reference Error

### ISSUE THREAD

**Issue by akojif** [TarikHuber/react-most-wanted#171]
Compiles successfully but displays Reference Error in browser.

ReferenceError
pt_messages is not defined
Call Stack
 Module.
  main.demo.js:1000:13
 Module../demo/src/config/locales/index.js
  main.demo.js:1020:30
 __webpack_require__
  demo.js:874:31
 fn
  demo.js:151:20
 Module.
  main.demo.js:1246:67
 Module../demo/src/config/menuItems.js
  main.demo.js:1615:30
 __webpack_require__
  demo.js:874:31
 fn
  demo.js:151:20
 Module.
  main.demo.js:16:68
 Module../demo/src/config/config.js
  main.demo.js:104:30

@TarikHuber I'll appreciate a solution to this problem

**Comment by TarikHuber** [comment]
Hi @akojif 
what package did you try? Is it rmw-shell-new?

**Comment by akojif** [comment]
No, rmw-shell

**Comment by akojif** [comment]
What could be the problem? I really need this to work  : (

**Comment by TarikHuber** [comment]
@akojif don't vory we will fix this.
Can you paste here your code from the file `/demo/src/config/locales/index.js`

And did you fork the projekt or used one of the scripts from the README?

**Comment by akojif** [comment]
@TarikHuber 
I downloaded the project as a zip file, then I took out rmw-shell folder from the packages and run npm install

Code from `/demo/src/config/locales/index.js`

`import en_messages from './en'
import de_messages from './de'
import ru_messages from './ru'
import bs_messages from './bs'
import es_messages from './es'
import fr_messages from './fr'
import '@formatjs/intl-relativetimeformat/polyfill'
import '@formatjs/intl-relativetimeformat/dist/locale-data/de'
import '@formatjs/intl-relativetimeformat/dist/locale-data/en'
import '@formatjs/intl-relativetimeformat/dist/locale-data/ru'
import '@formatjs/intl-relativetimeformat/dist/locale-data/bs'
import '@formatjs/intl-relativetimeformat/dist/locale-data/es'
import '@formatjs/intl-relativetimeformat/dist/locale-data/fr'
import '@formatjs/intl-relativetimeformat/dist/locale-data/pt'

const locales = [
  {
    locale: 'en',
    messages: en_messages,
  },
  {
    locale: 'de',
    messages: de_messages,
  },
  {
    locale: 'bs',
    messages: bs_messages,
  },
  {
    locale: 'ru',
    messages: ru_messages,
  },
  {
    locale: 'es',
    messages: es_messages,
  },
  {
    locale: 'fr',
    messages: fr_messages,
  },
  {
    locale: 'pt',
    messages: pt_messages,
  }
]

export default locales
`

**Comment by TarikHuber** [comment]
OK.

If you want to help me with this projekt you can do it that way as you did and send PRs to this project. 

If you want to create a new React project pls use this script: `npx create-react-app my-app --template rmw``
That will create a fresh and clean React project on your machine.

And now to your Error: It's because you use `pt_messages` in your code but don't declare or import that variable. As you can see we import with `import fr_messages from './fr'` the `fr_messages` and use it down in the code but the `pt_messages` are not imported.

You can just copy the `en_messages` file, rename it and then import it in your `/demo/src/config/locales/index.js` file.

I hope this helps. Let me know if you need any further help.

**Comment by akojif** [comment]
@TarikHuber 
Okay, thanks. Let me try it out
By the way, does creating a new React project give me everything i.e the homepage, authentication and dashboard?

**Comment by TarikHuber** [comment]
@akojif yes it gives you even more than on the demo you used with the copy. 
You will also use my React Most Wanted Firebase project as default with already some data in it.

To change that you can first login to your firebase account using the CLI and the run the commmand `firebase use --add` to add you project instead of mine. But if you only want to checkout react and play with it you can stay with the RMW Firebase project. But you can't change anything on the backend.

**Comment by akojif** [comment]
Oh, wow
Thanks. I really appreciate @TarikHuber

I'll definitely reach out if I encounter any other issue.

**Comment by TarikHuber** [comment]
@akojif you can always write me on twitter or an email 😄 

Can I close this issue?

**Comment by akojif** [comment]
Your Twitter handle?
Yes, you can close the issue.

**Comment by TarikHuber** [comment]
https://twitter.com/TarikHuber
