### ISSUE TITLE
SuperSelectField multiple does not work 

### ISSUE THREAD

**Issue by WoodyPhil** [TarikHuber/react-most-wanted#27]
Hi,

i´m trying to make the "helper" Dropdown in the Taskfom.js multiple selectable like this
![image](https://user-images.githubusercontent.com/7937191/36399444-36702c34-15cc-11e8-9e2c-925aafd496dc.png)

Soh i set multiple to true
![image](https://user-images.githubusercontent.com/7937191/36399465-5054d410-15cc-11e8-855e-ea2fb712690a.png)

But when i click on a field in the dropdownmenu nothing happens.
I think i´m just missing something.
Would be very nice to get a hint.

Best regards

**Comment by TarikHuber** [comment]
Hi @WoodyPhil ,

Thx for the info. I took a look on it and it seems that the issue comes from SuperSelectField itself. 

I wrote there a [issue](https://github.com/Sharlaan/material-ui-superselectfield/issues/135).

I was also thinking that the issue could be in the Redux-Form implementation of SuperSelectField but in the end I copied a example from SuperSeelctField and the same issue appears even I used it without the `Field` wrapper.

**Comment by Sharlaan** [comment]
Hi @WoodyPhil i'm author of SuperSelectField

I just released v1.8.9 can you retry with it ?
I think you should get an error about invalid value prop ?

**Comment by TarikHuber** [comment]
Hi @Sharlaan and @WoodyPhil , will check this tomorrow to. Thx for the feedback @Sharlaan 😄

**Comment by WoodyPhil** [comment]
@TarikHuber are there any updates about this?

**Comment by WoodyPhil** [comment]
@TarikHuber very nice, do you have any idea when the migration to MUI V1 will be completed?

**Comment by TarikHuber** [comment]
Closing this because Superselect field will no longer be used in this project.
