### ISSUE TITLE
Hello this is not a big issue, just personal issue

### ISSUE THREAD

**Issue by mdsadiqueinam** [TarikHuber/react-most-wanted#311]
Hello I am beginner in web development
I am trying to build a social media app like facebook for my personal project using material-ui-shell, but I am lost here, I have no idea what is happening in here and how can I implement or edit this on my app .
Any help would be appreciated.

Thank you

**Comment by TarikHuber** [comment]
To be honest. If you don't know what is happening there try first to work on smaller projects and the to make something similar to Facebook. It looks easy to build but just for those who don't know what everything needs to be behind it to work as it works. I mad this projct and doesnds of them more, I teach development of apps and I would not dare to do something like Facebook. 

I would realy recommend to start with smaller and easier projects and then go bigger with time and experience. This here is just for issues with this project. We can't provide you any examples on how to do it because no one here I know did it and even if this would not be the space to share stuff like that.

I used the `rmw-shell` package to make apps with some features of Facebook but it's just "some" and not nearly close to it as someone would expect it to be.
