### ISSUE TITLE
My accounts customization

### ISSUE THREAD

**Issue by sobiso** [TarikHuber/react-most-wanted#33]
How i can add some fields in My Account section ?

**Comment by TarikHuber** [comment]
Hi @sobiso ,

There are more ways to do this.

1. Use the `onAuthStateChanged` property in the config file of witch is a functions that is called when the user state changes (also login) and it has as property the `user` object. There you could add some default values or sync the user to another database like `firestore`

2. You can create your own `MyAccount` component and add it to your project routes under `/my_account`. This will override the default `MyAccount`. This works with every default component of `rmw-shell`

3. My Favorite. And this we use in our enterprice application in production witch is based on this project. This is the reason that we support it so much. For more data for the user create additional components and UI that indicate those. The reason for this is that sometimes the data you want to save should not be changed by the user just read and that would be hard organise in firebase if you save all of it at the same place. I see it like best practice to seperate data with different concepts to ensure the database rules can be set seperately.

Also I would recommend that you work with the `next` branch. It will replace the main one very soon and it hase a lot of breaking changes. Not because of use. Material UI V1 is just to different from the old one and all of the breaking changes come from that.

Let me know if you have more questions or need help with something.

**Comment by sobiso** [comment]
First... thank for fast response. 
Second... i will try this `next` branch and create additional component for Address data

**Comment by sobiso** [comment]
Is there any way to add some items in user menu (My account, Sign Out)?

**Comment by TarikHuber** [comment]
Hmmm not for now. But if you need it I can add that feature to the `next` branch. Just let me know.

**Comment by sobiso** [comment]
So the only way to do this is changing rmw-shell ? I think that this option (add some other items) will be nice feature.

**Comment by TarikHuber** [comment]
OK. Will se to add it tomorrow.

**Comment by TarikHuber** [comment]
Version 3.1.0 of 'rmw-shell' has now the feature to add a custom auth menu. To have any menu at all for auth you have to change your `menuItems.js` file. Use the props `isAuthMenu` and `handleSignOut` and add this before your menu list return:

```js
  if (isAuthMenu) {
    return [
      {
        value: '/my_account',
        primaryText: intl.formatMessage({ id: 'my_account' }),
        leftIcon: <AccountBoxIcon />
      },
      {
        value: '/signin',
        onClick: handleSignOut,
        primaryText: intl.formatMessage({ id: 'sign_out' }),
        leftIcon: <LockIcon />
      }
    ]
  }

return [
//your usual menu
]
````
