### ISSUE TITLE
sample code for firestore usage

### ISSUE THREAD

**Issue by 4mitabh** [TarikHuber/react-most-wanted#58]
Tarik,
Is there any sample code for firestore usage ?

I remember, you had a collection and document sample few months ago.
It seems to have been removed now.

**Comment by TarikHuber** [comment]
Hi @4mitabh ,

I'm happy that you didn't even notice it. It proves how simple the code is ;)
The tasks are an example of Collections and documents but already with the whole UI around it.

To just use collection and documents you can use instead of `watchList` => `watchCol` and instead of `watchPath` => `watchDoc` . Everything else around it stays the same. The array of the watched collection has not key and val but key and data as elements in it. 

Just let me know if you need more help on this.

**Comment by 4mitabh** [comment]
That's awesome!
I'll take a look at it today.

Thanks much.

**Comment by 4mitabh** [comment]
Works perfectly.

Thank you!
